name: Deploy Shiny App

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.3'

      - name: Restore renv environment
        uses: r-lib/actions/renv@v2

      - name: Deploy to Shinyapps.io
        env:
          SHINYAPPS_ACCOUNT: ${{ secrets.SHINYAPPS_ACCOUNT }}
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
          APP_NAME: shiny_meal
        run: |
          install.packages("rsconnect")
          rsconnect::deployApp(appDir = ".",
                               appName = "${{ env.APP_NAME }}",
                               account = "${{ env.SHINYAPPS_ACCOUNT }}",
                               upload = TRUE,
                               launch.browser = FALSE)